### ISSUE TITLE
Question: Why livelog on each worker instance instead externally

### ISSUE THREAD

**Issue by sheerun** [taskcluster/livelog#10]
From what I read, you put a livelog instance in each generic-worker.

Woudn't it be better to host livelog externally and just specify its address in generic-worker?

This way logs would survive worker's crash for example.

// edit You'd also woudn't need to setup domains for reading logs with stateless-dns-server

**Comment by jonasfj** [comment]
> Woudn't it be better to host livelog externally and just specify its address in generic-worker?

Then we would have to do actual authentication for the PUT request. The reason we don't do this is that in most cases nobody looks at the livelog. The tasks are short lived, and once they are completed the log is uploaded to S3.

So unless someone is opening the log viewing and streaming the livelog down while the task is running... All the livelogger does is to listen on a port and write input data to a file. This doesn't cost much, hence, if nobody looks at the log the cost of making it available as a livelog is small..

Also if we had an external service that service could easily get overloaded as we scale up the number of workers. And we would have issues with having this service in every aws region. 

And as there aren't many people looking at the live log at the same time, the worker can easily handle serving the request. In fact livelogging is really a best-effort service. We promise that logs are in S3, once the task is done, but if the worker crashes before the task is done, another worker will be assigned the task and the log is less important.

It's a pro/con senario. Since most tasks runs without someone fetching the log (at runtime), we prefer to pay as little overhead as possible. This way the overhead of offering the livelog is next to nothing, if it isn't requested by anyone.

At the end of the day we want to execute tasks fast and efficiently, not serve live logs :)

**Comment by jonasfj** [comment]
> This way logs would survive worker's crash for example.

Indeed, this is the hard part. As it could be relevant in the case where the task causes a worker crash.
However, in that case we really should be looking at the worker log (which is piped to papertrail) and not the task log.

> // edit You'd also woudn't need to setup domains for reading logs with stateless-dns-server

That's true, but stateless-dns-server is actually a pretty neat way of getting temporary domain names with very little overhead. Hosting `stateless-dns-server` isn't entirely fun, but with docker + tutum.co it's really just one or two t1.micro nodes :)

**Comment by jonasfj** [comment]
To be honest, I think that the for the generic-worker we should refactor the livelog into being a library that we use inside the worker. That way there is a one process less to deal with; I guess is sub-optimal in terms of isolation and stability, but how often does a go server crash anyways (especially if we limit it to never serve more than 10 livelog requests at the same time).

This way we cut away the cost of inter-process communication, and livelog (if not requested) wouldn't cost more than what it costs to store a file on disk and upload it to S3 afterwards.

Also it would be easier to deploy the generic-worker, as there is just one binary to drop in. And now dealing with some random port being used for data between livelog and task.

**Comment by sheerun** [comment]
I agree it would be better to embed livelog. HTTP interface only makes sense when hosting it on entirely different machine, and sharing between services (of course except GET part).

**Comment by jonasfj** [comment]
I think the reason it was done... was to put livelog in a docker container on linux...

It makes sense for better isolation, but I'm not sure it's worth the overhead in the long run.

**Comment by sheerun** [comment]
OK, thank you for answering. Personally I'd remove livelog from worker itself and hosted it somewhere else, but I understand the decision.

**Comment by jonasfj** [comment]
hmm... I suspect that in some cases (when it comes to machine in the data center) we will be forced to do that too (or use ngrok). But hopefully, it won't have to be all workers, as we spew out a lot of logs, most of which is never read :)

**Comment by sheerun** [comment]
(but moving livelog to library would be a great simplification, currently configuraton is little painful)

**Comment by jonasfj** [comment]
agreed, it would also reduce process overhead (memory and IPC).

**Comment by jonasfj** [comment]
FYI, if curious feel free to take a look at:
https://github.com/taskcluster/taskcluster-worker

I've been outlining a cleaner design for the worker... We plan to implement both docker-worker, windows and mac workers with the same code base. So they all share the same features, livelog, interactive shell and noVNC.

It's still just at design phase, code won't even compile.. We're just outlining interfaces.

**Comment by sheerun** [comment]
I also plan to create simplified docker worker (and with abstracted queue), so maybe we can join forces.

**Comment by jonasfj** [comment]
I think for `taskcluster-worker` we'll split the polling logic from all the docker and windows specific logic... So it should be increasingly feasible to use the interfaces in a worker for a completely different system.

**Comment by jonasfj** [comment]
Well, maybe... I have to say our focus is TaskCluster which has a lot of concepts dictacted from our server side queue. Things like tasks have artifacts, result state and other things, and there is well-defined APIs through which they are generated.

But some of the interface would likely be generic...

**Comment by sheerun** [comment]
I'd vote for webpack-like or babel-like plugin system. So only sketch of logic at the worker level and all the rest as "middleware" plugins.

**Comment by sheerun** [comment]
(where middleware is a function that takes current context, depending plugin site, and returns a new context). Plugins can also define new plugin attachment points (e.g. livelogger plugin can create plug spot for processing logs).

**Comment by jonasfj** [comment]
The outline for the interface is reasonably solid:
https://github.com/taskcluster/taskcluster-worker/blob/master/plugins/plugin.go#L27-L78

Essentially, plugins just hook into the task processing loop, at different stages of the loop. Which gives them different interfaces for the docker container or process running...
Consider the plugins observes of the task execution, but observes able to call in and modify the task execution, whether that is reading data from the task or interacting with the task as proxies etc might do.

**Comment by jonasfj** [comment]
So one of the benefits with go is static type safety... I fear one could easily throw that away, by trying to make it too dynamic...

I'm not sure I see how to do the middleware thing. it's essentially a chain-of-responsibility pattern.

**Comment by sheerun** [comment]
I'm no go-lang expert, but I think it would be better if plugin's context was just an interface specified by plugin (engine.Sandbox can be one of fields in context, but it shouldn't be the context itself). Then we could use go's structural typing to test whether plugin can be plugged at specific plug-site. If would also make it possible to include extra fields to context in future.

**Comment by sheerun** [comment]
Maybe something like: https://github.com/progrium/go-extpoints
